### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by vvs-** [mmasdeu/topologygame#4]
Congratulations with implementing such an application with GH actions.

But I guess that you don't want to keep all the `gh-pages` history, though. It will hit GH size [limits](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github) pretty soon. It will also make the repository clones and PRs a pain. The best practice is to keep only the last `gh-pages` commit and overwrite it every time with the new content, usually with force push (the same as how it was implemented in theorem_proving_in_lean4 repository).

**Comment by mmasdeu** [comment]
Thanks for the feedback! I changed the action that I'm using to one that clears all history on gh-pages. I think this should work!
